"""
LLM Client for API communication with AI models.

Supports multiple providers and models for different agents.
"""

import os
import json
import logging
import requests
from typing import Dict, Any, Optional, List
from dataclasses import dataclass
from abc import ABC, abstractmethod

@dataclass
class LLMConfig:
    """Configuration for LLM providers."""
    provider: str  # 'openai', 'anthropic', 'local', etc.
    model: str
    api_key: Optional[str] = None
    base_url: Optional[str] = None
    temperature: float = 0.7
    max_tokens: int = 2000

class LLMProvider(ABC):
    """Abstract base class for LLM providers."""
    
    @abstractmethod
    def generate_response(self, prompt: str) -> str:
        """Generate response from the LLM."""
        pass

class OpenAIProvider(LLMProvider):
    """OpenAI API provider."""
    
    def __init__(self, config: LLMConfig):
        self.config = config
        self.api_key = config.api_key or os.getenv('OPENAI_API_KEY')
        if not self.api_key:
            # Fallback to mock responses for testing
            self.api_key = None
            print("Warning: OpenAI API key not found. Using mock responses for testing.")
    
    def generate_response(self, prompt: str) -> str:
        """Generate response using OpenAI API."""
        if not self.api_key:
            # Return mock response for testing
            return self._get_mock_response(prompt)
        
        headers = {
            'Authorization': f'Bearer {self.api_key}',
            'Content-Type': 'application/json'
        }
        
        data = {
            'model': self.config.model,
            'messages': [{'role': 'user', 'content': prompt}],
            'temperature': self.config.temperature,
            'max_tokens': self.config.max_tokens
        }
        
        try:
            response = requests.post(
                'https://api.openai.com/v1/chat/completions',
                headers=headers,
                json=data,
                timeout=60
            )
            response.raise_for_status()
            
            result = response.json()
            return result['choices'][0]['message']['content']
            
        except requests.exceptions.RequestException as e:
            logging.error(f"OpenAI API error: {e}")
            return f"Error: {str(e)}"
    
    def _get_mock_response(self, prompt: str) -> str:
        """Return mock response for testing without API key."""
        if "even numbers" in prompt.lower():
            return """
Structured Problem: Prove that the sum of two even numbers is even.

Lean 4 Theorem:
```lean
theorem even_add_even (a b : ℕ) (ha : Even a) (hb : Even b) : Even (a + b) := 
```

Draft Proof: Let a and b be even numbers. Then a = 2k and b = 2l for some integers k and l. Therefore, a + b = 2k + 2l = 2(k + l), which is even by definition.
"""
        else:
            return "Mock response for testing: This would normally be generated by the LLM."

class LocalProvider(LLMProvider):
    """Local LLM provider (for free reasoning models)."""
    
    def __init__(self, config: LLMConfig):
        self.config = config
        self.base_url = config.base_url or 'http://localhost:11434'
    
    def generate_response(self, prompt: str) -> str:
        """Generate response using local LLM."""
        try:
            # Example for Ollama
            data = {
                'model': self.config.model,
                'prompt': prompt,
                'stream': False
            }
            
            response = requests.post(
                f'{self.base_url}/api/generate',
                json=data,
                timeout=120
            )
            response.raise_for_status()
            
            result = response.json()
            return result.get('response', '')
            
        except requests.exceptions.RequestException as e:
            logging.error(f"Local LLM error: {e}")
            return f"Error: {str(e)}"

class LLMClient:
    """Client for managing LLM interactions."""
    
    def __init__(self, config: LLMConfig):
        self.config = config
        self.logger = logging.getLogger(__name__)
        
        # Initialize appropriate provider
        if config.provider == 'openai':
            self.provider = OpenAIProvider(config)
        elif config.provider == 'local':
            self.provider = LocalProvider(config)
        else:
            raise ValueError(f"Unsupported provider: {config.provider}")
    
    def generate_response(self, prompt: str) -> str:
        """Generate response from configured LLM."""
        self.logger.info(f"Generating response with {self.config.provider}/{self.config.model}")
        return self.provider.generate_response(prompt)
    
    @classmethod
    def create_formalizer_client(cls) -> 'LLMClient':
        """Create LLM client for formalizer agent (lightweight model)."""
        config = LLMConfig(
            provider='openai',  # or 'local' for free models
            model='gpt-3.5-turbo',  # lightweight model
            temperature=0.3,  # more deterministic for formalization
            max_tokens=1000
        )
        return cls(config)
    
    @classmethod
    def create_proof_generator_client(cls) -> 'LLMClient':
        """Create LLM client for proof generator agent (strong reasoning model)."""
        config = LLMConfig(
            provider='openai',  # or 'local' for free models
            model='gpt-4',  # stronger reasoning model
            temperature=0.7,  # more creative for proofs
            max_tokens=2000
        )
        return cls(config)